SET fish_color_autosuggestion:808080
SET fish_color_command:ffd75f
SET fish_color_comment:af8787
SET fish_color_cwd:green
SET fish_color_cwd_root:red
SET fish_color_end:00FF00
SET fish_color_error:ff5f5f
SET fish_color_escape:cyan
SET fish_color_history_current:cyan
SET fish_color_host:normal
SET fish_color_match:cyan
SET fish_color_normal:normal
SET fish_color_operator:cyan
SET fish_color_param:00afff
SET fish_color_quote:725000
SET fish_color_redirection:normal
SET fish_color_search_match:\x2d\x2dbackground\x3dpurple
SET fish_color_selection:\x2d\x2dbackground\x3dpurple
SET fish_color_status:red
SET fish_color_user:green
SET fish_color_valid_path:\x2d\x2dunderline